# Generated by Django 5.1.4 on 2024-12-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhotelsite', '0005_room_user_alter_hotel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
