# Generated by Django 5.1.4 on 2024-12-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhotelsite', '0008_rename_user_room_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_name',
            new_name='user',
        ),
    ]
